/* eslint-disable */
// Auto-generated by scripts/generate-biz-care-misc-skus.mjs — do not edit.

export const BIZ_CARE_MISCELLANEOUS_SKUS_UPPER = new Set<string>([
  "C602W",
  "C603U",
  "CA044U",
  "CCS149U",
  "CCS250U",
  "CH248L",
  "CSC245U",
  "CSC246U",
  "CSC249U",
]);
